# Generated by Django 4.2.30 on 2026-05-14 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                ("id", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("data", models.JSONField()),
                ("published", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                ("id", models.CharField(max_length=255, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=64,
                    ),
                ),
                ("data", models.JSONField()),
                (
                    "domain",
                    models.ForeignKey(
                        db_column="domain_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="bench.domain",
                        to_field="id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                ("id", models.CharField(max_length=255, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("timeout", "Timeout"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=64,
                    ),
                ),
                ("data", models.JSONField()),
                (
                    "run",
                    models.ForeignKey(
                        db_column="run_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        to="bench.run",
                        to_field="id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Leaderboard",
            fields=[
                ("id", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("model", models.CharField(max_length=255)),
                ("primary_score", models.FloatField()),
                ("data", models.JSONField()),
                (
                    "domain",
                    models.ForeignKey(
                        db_column="domain_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_entries",
                        to="bench.domain",
                        to_field="id",
                    ),
                ),
                (
                    "run",
                    models.OneToOneField(
                        db_column="run_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_entry",
                        to="bench.run",
                        to_field="id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeveloperEnvironment",
            fields=[
                ("id", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("owner_id", models.CharField(db_index=True, max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("github_url", models.URLField(max_length=512)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("cloning", "Cloning"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=64,
                    ),
                ),
                ("env_url", models.URLField(blank=True, max_length=512, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        db_column="domain_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="developer_environments",
                        to="bench.domain",
                        to_field="id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BenchJob",
            fields=[
                ("id", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("github_url", models.URLField(max_length=512)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=64,
                    ),
                ),
                ("model_results", models.JSONField(blank=True, null=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        db_column="domain_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bench_jobs",
                        to="bench.domain",
                        to_field="id",
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        db_column="env_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bench_jobs",
                        to="bench.developerenvironment",
                        to_field="id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnvironmentUsage",
            fields=[
                ("id", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("model", models.CharField(max_length=255)),
                ("episode_count", models.IntegerField(default=0)),
                ("primary_score", models.FloatField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "domain",
                    models.ForeignKey(
                        db_column="domain_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="bench.domain",
                        to_field="id",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        db_column="run_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="bench.run",
                        to_field="id",
                    ),
                ),
            ],
        ),
    ]
