# Generated by Django 4.2.30 on 2026-05-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BenchJob',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('env_id', models.CharField(db_index=True, max_length=255)),
                ('domain_id', models.CharField(blank=True, max_length=255, null=True)),
                ('github_url', models.CharField(max_length=512)),
                ('status', models.CharField(db_index=True, default='queued', max_length=64)),
                ('model_results', models.TextField(blank=True, null=True)),
                ('claimed_at', models.CharField(blank=True, max_length=64, null=True)),
                ('completed_at', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='DeveloperEnvironment',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('github_url', models.CharField(max_length=512)),
                ('status', models.CharField(default='pending', max_length=64)),
                ('domain_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('env_url', models.CharField(blank=True, max_length=512, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('data', models.TextField()),
                ('published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentUsage',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('domain_id', models.CharField(db_index=True, max_length=255)),
                ('run_id', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('episode_count', models.IntegerField(default=0)),
                ('primary_score', models.FloatField(blank=True, null=True)),
                ('timestamp', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('run_id', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(default='pending', max_length=64)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('domain_id', models.CharField(db_index=True, max_length=255)),
                ('run_id', models.CharField(max_length=255, unique=True)),
                ('model', models.CharField(max_length=255)),
                ('primary_score', models.FloatField()),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('domain_id', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(default='pending', max_length=64)),
                ('data', models.TextField()),
            ],
        ),
    ]
