# Generated by Django 4.2.30 on 2026-05-26 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bench", "0007_remove_run_environment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="benchjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="queued",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="developerenvironment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("cloning", "Cloning"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="pending",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="episode",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("timeout", "Timeout"),
                ],
                db_index=True,
                default="pending",
                max_length=64,
            ),
        ),
    ]
